services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   env_file: .env
  #   depends_on:
  #     - postgres
  #     - s3ninja
  #   networks:
  #     - my-network

  postgres:
    hostname: database.local
    image: postgres:15-alpine
    env_file: .env.local
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  # s3ninja:
  #   hostname: storage.local
  #   image: scireum/s3-ninja:latest
  #   expose:
  #     - '9000'
  #   volumes:
  #     - ./docker/storage_data:/home/sirius/data
  #   networks:
  #     - my-network
  ## S3 Service
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker/minio-storage:/home/data
    command: server --console-address ":9001" /data
    env_file: .env.local
    restart: always

volumes:
  postgres_data:
  s3ninja_data:

networks:
  my-network:
    driver: bridge
